krijgt krijg
gebruikt gebruik
begint begin
dienst diens
internet interne
vraagt vraag
brengt breng
bereikt bereik
vertelt vertel
spreekt spreek
schrijft schrijf
levert lever
probeert probeer
draagt draag
draait draai
betaalt betaal
groeit groei
schijnt schijn
talent talen
ontvangt ontvang
reageert reageer
gelukt geluk
gelooft geloof
geniet genie
verloopt verloop
verliest verlies
steekt steek
begrijpt begrijp
eindigt eindig
verkoopt verkoop
vertrekt vertrek
stuurt stuur
vreest vrees
gemist gemis
steunt steun
verwijst verwijs
belooft beloof
bedoelt bedoel
herinnert herinner
constateert constateer
slaagt slaag
beschouwt beschouw
vertoont vertoon
bewijst bewijs
beseft besef
overweegt overweeg
bekijkt bekijk
rekent reken
verkeert verkeer
adviseert adviseer
vliegt vlieg
streeft streef
regelt regel
luistert luister
behandelt behandel
tekent teken
schept schep
bevalt beval
springt spring
geschiedt geschied
bezoekt bezoek
misbruikt misbruik
ondersteunt ondersteun
inhoudt inhoud
vervalt verval
vermoedt vermoed
besteedt besteed
regent regen
drinkt drink
grijpt grijp
controleert controleer
verbaast verbaas
slaapt slaap
herkent herken
schuilt schuil
handelt handel
verschilt verschil
schetst schets
ervaart ervaar
vermeldt vermeld
voorspelt voorspel
klaagt klaag
twijfelt twijfel
oordeelt oordeel
schuift schuif
oproept oproep
smaakt smaak
grootst groots
verblijft verblijf
onderscheidt onderscheid
beleeft beleef
behoudt behoud
verbetert verbeter
beoordeelt beoordeel
straalt straal
creëert creëer
uitvoert uitvoer
realiseert realiseer
bedenkt bedenk
begeleidt begeleid
nadert nader
vervolgt vervolg
stroomt stroom
baseert baseer
beantwoordt beantwoord
beheert beheer
belandt beland
vergelijkt vergelijk
vervangt vervang
gedraagt gedraag
kenmerkt kenmerk
verdiept verdiep
herhaalt herhaal
verhuist verhuis
accepteert accepteer
verzekert verzeker
stoort stoor
verdedigt verdedig
tegenkomt tegenkom
snijdt snijd
verlangt verlang
profiteert profiteer
ondervindt ondervind
terugkomt terugkom
bekent beken
terugkeert terugkeer
schreeuwt schreeuw
kruipt kruip
bespreekt bespreek
schrikt schrik
vertrouwt vertrouw
droomt droom
bespaart bespaar
onderhoudt onderhoud
veronderstelt veronderstel
betreurt betreur
verzamelt verzamel
combineert combineer
schenkt schenk
verspreidt verspreid
bestrijdt bestrijd
onderdrukt onderdruk
beïnvloedt beïnvloed
bloeit bloei
herstelt herstel
vertaalt vertaal
worstelt worstel
traint train
schudt schud
concentreert concentreer
informeert informeer
studeert studeer
vergist vergis
passeert passeer
koestert koester
verbruikt verbruik
noteert noteer
oefent oefen
wisselt wissel
schort schor
onderschrijft onderschrijf
zwijgt zwijg
overleeft overleef
gesleept gesleep
aanvaardt aanvaard
betoogt betoog
aanneemt aanneem
schakelt schakel
ergert erger
zwaait zwaai
vermaakt vermaak
blaast blaas
bemoeit bemoei
herbergt herberg
trouwt trouw
schildert schilder
verdeelt verdeel
begeeft begeef
benadert benader
uitvalt uitval
betrekt betrek
wijzigt wijzig
citeert citeer
rechtvaardigt rechtvaardig
claimt claim
bewaart bewaar
verraadt verraad
registreert registreer
wandelt wandel
verwerpt verwerp
opstelt opstel
handhaaft handhaaf
benoemt benoem
schrapt schrap
selecteert selecteer
negeert negeer
glijdt glijd
spaart spaar
sleept sleep
verwijdert verwijder
formuleert formuleer
beveelt beveel
bestudeert bestudeer
gekraakt gekraak
analyseert analyseer
mooist moois
nadenkt nadenk
juicht juich
meeneemt meeneem
schommelt schommel
getikt getik
veroordeelt veroordeel
samenhangt samenhang
afvraagt afvraag
verdenkt verdenk
rondloopt rondloop
glimlacht glimlach
format forma
waardeert waardeer
riskeert riskeer
toetst toets
bestelt bestel
respecteert respecteer
meemaakt meemaak
belegt beleg
consult consul
voorbereidt voorbereid
verkiest verkies
verwoordt verwoord
overtuigt overtuig
berekent bereken
doorloopt doorloop
betwijfelt betwijfel
steelt steel
belangrijkst belangrijks
koppelt koppel
zweeft zweef
verkrijgt verkrijg
hekelt hekel
financiert financier
motiveert motiveer
krimpt krimp
aarzelt aarzel
zetelt zetel
staakt staak
onthoudt onthoud
verveelt verveel
verzint verzin
communist communis
betreedt betreed
refereert refereer
geklopt geklop
bekleedt bekleed
geneest genees
communiceert communiceer
aankijkt aankijk
verkondigt verkondig
fluistert fluister
markeert markeer
irriteert irriteer
verheugt verheug
verbergt verberg
ontkomt ontkom
onderkent onderken
vergoedt vergoed
beraadt beraad
bestrijkt bestrijk
schaamt schaam
protesteert protesteer
vernietigt vernietig
vriest vries
strijkt strijk
verdraagt verdraag
zachtst zachts
serveert serveer
kraakt kraak
schuwt schuw
hergebruikt hergebruik
ontneemt ontneem
vermijdt vermijd
oppert opper
waarborgt waarborg
verhuurt verhuur
overhoudt overhoud
scheurt scheur
uitbrengt uitbreng
slingert slinger
leukst leuks
graaft graaf
uitloopt uitloop
thuiskomt thuiskom
prikkelt prikkel
schopt schop
interpreteert interpreteer
uitkijkt uitkijk
schaart schaar
verwelkomt verwelkom
strookt strook
tovert tover
beziet bezie
definieert definieer
hindert hinder
tablet table
mompelt mompel
zweert zweer
verbrandt verbrand
hamert hamer
terugkrijgt terugkrijg
wrijft wrijf
confronteert confronteer
beëindigt beëindig
corrigeert corrigeer
struikelt struikel
moedigt moedig
verneemt verneem
schaft schaf
waarneemt waarneem
overtreedt overtreed
grijnst grijns
scheert scheer
opstapt opstap
overwint overwin
uithaalt uithaal
kweekt kweek
gestampt gestamp
overvalt overval
volhoudt volhoud
installeert installeer
pretendeert pretendeer
moppert mopper
fotografeert fotografeer
moeilijkst moeilijks
spoelt spoel
verstuurt verstuur
invoert invoer
sluipt sluip
knijpt knijp
rommelt rommel
doorbrengt doorbreng
prefereert prefereer
rammelt rammel
beloont beloon
ververst ververs
ondertekent onderteken
verbeeldt verbeeld
vertoeft vertoef
smeekt smeek
focust focus
verkent verken
aanraakt aanraak
verleidt verleid
opzoekt opzoek
overhandigt overhandig
goedkeurt goedkeur
onderbreekt onderbreek
beschadigt beschadig
intrekt intrek
kleedt kleed
evalueert evalueer
timmert timmer
experimenteert experimenteer
bevrijdt bevrijd
beklaagt beklaag
streelt streel
aanvoert aanvoer
vervloekt vervloek
verklapt verklap
verontschuldigt verontschuldig
terugloopt terugloop
overdrijft overdrijf
lekkerst lekkers
stevent steven
aanmeldt aanmeld
wappert wapper
wankelt wankel
reserveert reserveer
verbreekt verbreek
verwondert verwonder
omarmt omarm
ijvert ijver
identificeert identificeer
ontaardt ontaard
bewondert bewonder
speurt speur
broedt broed
omdraait omdraai
nestelt nestel
spreidt spreid
beloopt beloop
raadpleegt raadpleeg
kraait kraai
ophaalt ophaal
schikt schik
logeert logeer
geklapt geklap
gekletst geklets
ontspant ontspan
terugvindt terugvind
voorlegt voorleg
observeert observeer
herdrukt herdruk
opmaakt opmaak
mijmert mijmer
dwaalt dwaal
ambieert ambieer
bladert blader
discrimineert discrimineer
opteert opteer
cachet cache
splitst splits
schorst schors
smeert smeer
sorteert sorteer
kleinst kleins
verdrinkt verdrink
zwerft zwerf
knippert knipper
couplet couple
geklikt geklik
parkeert parkeer
bemerkt bemerk
vergeeft vergeef
omhelst omhels
vloekt vloek
activeert activeer
verwart verwar
voorleest voorlees
verzuimt verzuim
overziet overzie
peinst peins
beoefent beoefen
kreunt kreun
integreert integreer
bezuinigt bezuinig
optrekt optrek
associeert associeer
strooit strooi
reinigt reinig
binnenstapt binnenstap
beledigt beledig
relaxt relax
terugkijkt terugkijk
poetst poets
trakteert trakteer
bekritiseert bekritiseer
opdoet opdoe
piekert pieker
extremist extremis
dondert donder
verlegt verleg
servet serve
verwarmt verwarm
bespeurt bespeur
vermengt vermeng
scheldt scheld
spendeert spendeer
acteert acteer
weerlegt weerleg
offert offer
verspeelt verspeel
kletst klets
voorhoudt voorhoud
isoleert isoleer
uitgroeit uitgroei
borrelt borrel
krabbelt krabbel
bekomt bekom
aanmaakt aanmaak
overloopt overloop
spookt spook
solliciteert solliciteer
treurt treur
sleurt sleur
verwaarloost verwaarloos
discussieert discussieer
kronkelt kronkel
preekt preek
bederft bederf
rechtsomkeert rechtsomkeer
kopieert kopieer
ontloopt ontloop
onderbouwt onderbouw
ontwijkt ontwijk
betuigt betuig
swingt swing
huldigt huldig
opschrijft opschrijf
manipuleert manipuleer
deinst deins
belijdt belijd
doorvoert doorvoer
ontdoet ontdoe
terugvalt terugval
spuugt spuug
projecteert projecteer
grossiert grossier
opheft ophef
hunkert hunker
volhardt volhard
pronkt pronk
opkijkt opkijk
flitst flits
bewandelt bewandel
vernieuwt vernieuw
speculeert speculeer
ontwaart ontwaar
broeit broei
sukkelt sukkel
checkt check
begeert begeer
schampert schamper
travestiet travestie
kwetst kwets
gepiept gepiep
klampt klamp
optelt optel
beklimt beklim
draaft draaf
verloochent verloochen
feliciteert feliciteer
slaakt slaak
borduurt borduur
distantieert distantieer
verzwijgt verzwijg
fantaseert fantaseer
oversteekt oversteek
inspecteert inspecteer
opzegt opzeg
ontzegt ontzeg
betoont betoon
afkeurt afkeur
verbouwt verbouw
verwent verwen
kriebelt kriebel
consumeert consumeer
behoedt behoed
kaatst kaats
loodst loods
bevreemdt bevreemd
crasht crash
omzeilt omzeil
schroomt schroom
binnenloopt binnenloop
terugziet terugzie
schuifelt schuifel
dreunt dreun
inkoopt inkoop
tolereert tolereer
kantelt kantel
gehoorzaamt gehoorzaam
schemert schemer
pendelt pendel
wantrouwt wantrouw
terugdenkt terugdenk
repareert repareer
boezemt boezem
versiert versier
huppelt huppel
gevloekt gevloek
instapt instap
uitdraait uitdraai
bekendst bekends
oriënteert oriënteer
repeteert repeteer
verspilt verspil
oppast oppas
contrat contra
verafschuwt verafschuw
programmeert programmeer
neervalt neerval
gejuicht gejuich
doorziet doorzie
evenaart evenaar
samenstelt samenstel
opendoet opendoe
sluimert sluimer
snuift snuif
vermenigvuldigt vermenigvuldig
verzendt verzend
ontraadt ontraad
verzandt verzand
toezegt toezeg
verdwaalt verdwaal
gedoogt gedoog
verbreedt verbreed
amuseert amuseer
opknapt opknap
componeert componeer
tempert temper
wentelt wentel
uitroept uitroep
stampt stamp
verteert verteer
ophangt ophang
verhardt verhard
afreist afreis
verwisselt verwissel
woekert woeker
vervreemdt vervreemd
schaatst schaats
hobbelt hobbel
doublet double
bekeert bekeer
duurst duurs
prettigst prettigs
verdraait verdraai
ageert ageer
verzuipt verzuip
jubelt jubel
weggooit weggooi
bemint bemin
doortrekt doortrek
stookt stook
monteert monteer
uitstapt uitstap
aanbeveelt aanbeveel
bagatelliseert bagatelliseer
beluistert beluister
aanschouwt aanschouw
fronst frons
halveert halveer
knielt kniel
zondigt zondig
knipoogt knipoog
stuitert stuiter
ratelt ratel
verrekt verrek
geknikt geknik
smoort smoor
afrondt afrond
vertikt vertik
ventileert ventileer
briest bries
scharrelt scharrel
afdrukt afdruk
opruimt opruim
schroeft schroef
huivert huiver
graait graai
begraaft begraaf
babbelt babbel
downloadt download
verslindt verslind
gepreekt gepreek
overlapt overlap
overwerkt overwerk
strompelt strompel
ontleedt ontleed
masseert masseer
sneert sneer
vaardigt vaardig
struint struin
verwondt verwond
terugblikt terugblik
plaagt plaag
complimenteert complimenteer
opvoedt opvoed
misleidt misleid
spettert spetter
ordent orden
excuseert excuseer
inhaalt inhaal
gekrast gekras
dompelt dompel
snuffelt snuffel
giechelt giechel
inhuurt inhuur
dobbert dobber
schraapt schraap
aanbidt aanbid
gebeukt gebeuk
gluurt gluur
inlogt inlog
manchet manche
attendeert attendeer
stottert stotter
sjouwt sjouw
eenvoudigst eenvoudigs
interessantst interessants
aanraadt aanraad
rondkijkt rondkijk
snoeit snoei
forceert forceer
deponeert deponeer
doorzoekt doorzoek
inloopt inloop
gevaarlijkst gevaarlijks
flikkert flikker
toejuicht toejuich
slentert slenter
verwittigt verwittig
doorhebt doorheb
plooit plooi
beveiligt beveilig
eerbiedigt eerbiedig
snurkt snurk
ontbrandt ontbrand
gedenkt gedenk
telefoneert telefoneer
wikkelt wikkel
afstudeert afstudeer
toetert toeter
braakt braak
vergrijpt vergrijp
opkoopt opkoop
fleurt fleur
permitteert permitteer
overdenkt overdenk
leegloopt leegloop
snoert snoer
inkomt inkom
zwiept zwiep
snauwt snauw
doneert doneer
uitleent uitleen
doorleest doorlees
toewenst toewens
staaft staaf
vergiftigt vergiftig
veroorlooft veroorloof
intrapt intrap
inruilt inruil
bedelt bedel
liefhebt liefheb
bloost bloos
klautert klauter
bengelt bengel
afhaalt afhaal
apprecieert apprecieer
fixeert fixeer
narcist narcis
kneedt kneed
priemt priem
thought though
slijpt slijp
aangroeit aangroei
knutselt knutsel
verblindt verblind
kenschetst kenschets
geneert geneer
wimpelt wimpel
floept floep
knabbelt knabbel
opvallendst opvallends
veulent veulen
knettert knetter
doorgroeit doorgroei
uitrolt uitrol
knoeit knoei
herleidt herleid
verstandigst verstandigs
benijdt benijd
zwiert zwier
kwakkelt kwakkel
davert daver
stippelt stippel
verblijdt verblijd
schaakt schaak
instart instar
doorstroomt doorstroom
kampeert kampeer
inbouwt inbouw
omkeert omkeer
dartelt dartel
mediteert mediteer
schurkt schurk
bakent baken
dribbelt dribbel
kiepert kieper
inwoont inwoon
stroopt stroop
opbloeit opbloei
zweemt zweem
bootst boots
verfoeit verfoei
inkijkt inkijk
zwabbert zwabber
meandert meander
generaliseert generaliseer
effent effen
vermaant vermaan
geselt gesel
willigt willig
aanroept aanroep
schaaft schaaf
kapittelt kapittel
aardigst aardigs
bestendigt bestendig
planet plane
sproeit sproei
afroept afroep
schrijnt schrijn
kuiert kuier
switcht switch
herschrijft herschrijf
uitwijkt uitwijk
takelt takel
fijnst fijns
aantrekkelijkst aantrekkelijks
navigeert navigeer
doorgrondt doorgrond
bevoorraadt bevoorraad
stompt stomp
verbreidt verbreid
uitrukt uitruk
screent screen
benieuwt benieuw
doorverkoopt doorverkoop
geprutst gepruts
orakelt orakel
